apiVersion: apps/v1
kind: Deployment
metadata:
  name: child-service-reactive
  labels:
    app: child-service-reactive
spec:
  replicas: 12
  selector:
    matchLabels:
      app: child-service-reactive
  template:
    metadata:
      labels:
        app: child-service-reactive
    spec:
      containers:
        - name: child-service-reactive-jvm
          image: __REGISTRY_URL__/__PROJECT_NAME__/child-service-reactive-jvm:latest
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
            - containerPort: 9091
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: child-service-reactive
  name: child-service-reactive
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jfr-jmx
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: child-service-reactive
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: child-service-reactive
  name: child-service-reactive
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: child-service-reactive
    weight: 100
  wildcardPolicy: None